version: "3"

services:
    backend:
        build: ./api
        expose: 
            - "5000"
        ports: 
            - "127.0.0.1:5000:5000"
        command: python api.py
        networks: 
            - app-test
    frontend:
        build: ./client
        expose: 
            - "3000"
        ports: 
            - "3000:3000"
        networks: 
            - app-test
        depends_on: 
            - backend
        links:
            - backend
        command: npm start

networks:
    app-test:
        driver: bridge
